// HTML Elements
var h = {
	topBar: "topBar",
	sideBar: "sideBar",
	rescalerL: "rescalerL",
	cWrapper: "cWrapper",
	editorBox: "editorBox",
	rescalerR: "rescalerR",
	previewBox: "previewBox",
	logo: "logo",
	signup: "signup",
	centeredText: "centeredText",
	centeredText2: "centeredText2",
	login: "login",
	eTable: "eTable",
	editHolder: "editHolder",
	canvasHolder: "canvasHolder",
	eTitle: "eTitle",
	pTitle: "pTitle",
	pTable: "pTable",
	eHeader: "eHeader",
	eMedia: "eMedia",
	eQuestion: "eQuestion",
	eAnswers: "eAnswers",
	eText: "eText",
	eHeaderInput: "eHeaderInput",
	pCanvas: "pCanvas",
	q1: "q1",
	q2: "q2",
	eInsertAnswer: "eInsertAnswer",
	playWrapper	: "playWrapper",
	accountWrapper: "accountWrapper",
	aboutWrapper: "aboutWrapper"
};